name: tfl_monitor
version: "0.0.1"
config-version: 2

profile: tfl_monitor

model-paths: ["models", "sources"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  tfl_monitor:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
