/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service liveness probe */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current operational status for every served line */
        get: operations["get_status_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historic line statuses over an arbitrary window */
        get: operations["get_status_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reliability/{line_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reliability score for a single line over a rolling window */
        get: operations["get_line_reliability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most recent disruptions, optionally scoped to a mode */
        get: operations["get_recent_disruptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bus/{stop_id}/punctuality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Punctuality statistics for a given bus stop */
        get: operations["get_bus_punctuality"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream an agent response over SSE */
        post: operations["post_chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{thread_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve messages for an existing chat thread */
        get: operations["get_chat_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            dependencies: {
                [key: string]: "ok" | "degraded" | "unreachable";
            };
        };
        LineStatus: {
            line_id: string;
            line_name: string;
            /** @enum {string} */
            mode: "tube" | "elizabeth-line" | "overground" | "dlr" | "bus" | "national-rail" | "river-bus" | "cable-car" | "tram";
            status_severity: number;
            status_severity_description: string;
            reason?: string | null;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to: string;
        };
        LineReliability: {
            line_id: string;
            line_name: string;
            mode: string;
            window_days: number;
            reliability_percent: number;
            sample_size: number;
            severity_histogram: {
                [key: string]: number;
            };
        };
        Disruption: {
            disruption_id: string;
            /** @enum {string} */
            category: "RealTime" | "PlannedWork" | "Information" | "Incident" | "Undefined";
            category_description: string;
            description: string;
            summary: string;
            affected_routes: string[];
            affected_stops: string[];
            closure_text: string;
            severity: number;
            /** Format: date-time */
            created: string;
            /** Format: date-time */
            last_update: string;
        };
        BusPunctuality: {
            stop_id: string;
            stop_name: string;
            window_days: number;
            on_time_percent: number;
            early_percent: number;
            late_percent: number;
            sample_size: number;
        };
        ChatRequest: {
            thread_id: string;
            message: string;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description RFC 7807 problem details. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
        };
    };
    responses: {
        /** @description Error response following RFC 7807. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "dependencies": {}
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    get_status_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live line statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "line_id": "victoria",
                     *         "line_name": "Victoria",
                     *         "mode": "tube",
                     *         "status_severity": 10,
                     *         "status_severity_description": "Good Service",
                     *         "reason": null,
                     *         "valid_from": "2026-04-22T07:00:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       },
                     *       {
                     *         "line_id": "piccadilly",
                     *         "line_name": "Piccadilly",
                     *         "mode": "tube",
                     *         "status_severity": 6,
                     *         "status_severity_description": "Severe Delays",
                     *         "reason": "Signal failure at Acton Town",
                     *         "valid_from": "2026-04-22T06:15:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       },
                     *       {
                     *         "line_id": "elizabeth",
                     *         "line_name": "Elizabeth line",
                     *         "mode": "elizabeth-line",
                     *         "status_severity": 9,
                     *         "status_severity_description": "Minor Delays",
                     *         "reason": "Earlier incident at Paddington",
                     *         "valid_from": "2026-04-22T05:30:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["LineStatus"][];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    get_status_history: {
        parameters: {
            query: {
                /** @description Restrict to a single line (e.g. `victoria`). */
                line_id?: string;
                /** @description Window start (UTC, inclusive). */
                from: string;
                /** @description Window end (UTC, exclusive). */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historic line statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "line_id": "victoria",
                     *         "line_name": "Victoria",
                     *         "mode": "tube",
                     *         "status_severity": 10,
                     *         "status_severity_description": "Good Service",
                     *         "reason": null,
                     *         "valid_from": "2026-04-20T05:30:00Z",
                     *         "valid_to": "2026-04-20T23:59:59Z"
                     *       },
                     *       {
                     *         "line_id": "victoria",
                     *         "line_name": "Victoria",
                     *         "mode": "tube",
                     *         "status_severity": 9,
                     *         "status_severity_description": "Minor Delays",
                     *         "reason": "Signalling issues earlier",
                     *         "valid_from": "2026-04-21T05:30:00Z",
                     *         "valid_to": "2026-04-21T23:59:59Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["LineStatus"][];
                };
            };
            400: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    get_line_reliability: {
        parameters: {
            query?: {
                /** @description Window size in days. */
                window?: number;
            };
            header?: never;
            path: {
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reliability summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "line_id": "victoria",
                     *       "line_name": "Victoria",
                     *       "mode": "tube",
                     *       "window_days": 7,
                     *       "reliability_percent": 94.2,
                     *       "sample_size": 2016,
                     *       "severity_histogram": {
                     *         "6": 12,
                     *         "9": 48,
                     *         "10": 1956
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["LineReliability"];
                };
            };
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    get_recent_disruptions: {
        parameters: {
            query?: {
                limit?: number;
                mode?: "tube" | "elizabeth-line" | "overground" | "dlr" | "bus" | "national-rail" | "river-bus" | "cable-car" | "tram";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent disruptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "disruption_id": "2026-04-22-PIC-001",
                     *         "category": "RealTime",
                     *         "category_description": "Real Time",
                     *         "description": "Signal failure at Acton Town, reduced service on Piccadilly.",
                     *         "summary": "Severe delays on Piccadilly line",
                     *         "affected_routes": [
                     *           "piccadilly"
                     *         ],
                     *         "affected_stops": [
                     *           "940GZZLUATN",
                     *           "940GZZLUACT"
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 6,
                     *         "created": "2026-04-22T06:15:00Z",
                     *         "last_update": "2026-04-22T08:05:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-ELI-001",
                     *         "category": "RealTime",
                     *         "category_description": "Real Time",
                     *         "description": "Earlier incident at Paddington affecting Elizabeth line.",
                     *         "summary": "Minor delays on Elizabeth line",
                     *         "affected_routes": [
                     *           "elizabeth"
                     *         ],
                     *         "affected_stops": [
                     *           "910GPADTON"
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 6,
                     *         "created": "2026-04-22T05:40:00Z",
                     *         "last_update": "2026-04-22T07:20:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-21-VIC-001",
                     *         "category": "PlannedWork",
                     *         "category_description": "Planned Work",
                     *         "description": "Engineering works affecting Victoria line weekend service.",
                     *         "summary": "Minor delays this weekend",
                     *         "affected_routes": [
                     *           "victoria"
                     *         ],
                     *         "affected_stops": [],
                     *         "closure_text": "No service between Seven Sisters and Walthamstow Central on Sunday.",
                     *         "severity": 9,
                     *         "created": "2026-04-18T12:00:00Z",
                     *         "last_update": "2026-04-21T09:00:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-PIC-002",
                     *         "category": "Information",
                     *         "category_description": "Information",
                     *         "description": "Lifts out of service at Holborn.",
                     *         "summary": "Step-free access affected",
                     *         "affected_routes": [
                     *           "piccadilly"
                     *         ],
                     *         "affected_stops": [
                     *           "940GZZLUHBN"
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 9,
                     *         "created": "2026-04-22T04:00:00Z",
                     *         "last_update": "2026-04-22T04:00:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-VIC-002",
                     *         "category": "Information",
                     *         "category_description": "Information",
                     *         "description": "Reduced frequency during morning peak due to staff shortage.",
                     *         "summary": "Change of frequency on Victoria line",
                     *         "affected_routes": [
                     *           "victoria"
                     *         ],
                     *         "affected_stops": [],
                     *         "closure_text": "",
                     *         "severity": 9,
                     *         "created": "2026-04-22T06:30:00Z",
                     *         "last_update": "2026-04-22T07:45:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Disruption"][];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    get_bus_punctuality: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Punctuality summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "stop_id": "490008660N",
                     *       "stop_name": "Trafalgar Square",
                     *       "window_days": 7,
                     *       "on_time_percent": 88.5,
                     *       "early_percent": 4.1,
                     *       "late_percent": 7.4,
                     *       "sample_size": 1240
                     *     }
                     */
                    "application/json": components["schemas"]["BusPunctuality"];
                };
            };
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    post_chat_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    get_chat_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "role": "user",
                     *         "content": "Which Tube line had the worst reliability last week?",
                     *         "created_at": "2026-04-20T14:12:00Z"
                     *       },
                     *       {
                     *         "role": "assistant",
                     *         "content": "The Piccadilly line averaged 87.5% reliability, the lowest of the network.",
                     *         "created_at": "2026-04-20T14:12:04Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
}
