/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service liveness probe */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current operational status for every served line */
        get: operations["get_status_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most recent disruptions, optionally scoped to a mode */
        get: operations["get_recent_disruptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream an agent response over SSE */
        post: operations["post_chat_stream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/{thread_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve messages for an existing chat thread */
        get: operations["get_chat_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthStatus: {
            /** @enum {string} */
            status: "ok" | "degraded";
            dependencies: {
                [key: string]: "ok" | "degraded" | "unreachable";
            };
        };
        LineStatus: {
            line_id: string;
            line_name: string;
            /** @enum {string} */
            mode: "tube" | "elizabeth-line" | "overground" | "dlr" | "bus" | "national-rail" | "river-bus" | "cable-car" | "tram";
            status_severity: number;
            status_severity_description: string;
            reason?: string | null;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to: string;
        };
        Disruption: {
            disruption_id: string;
            /** @enum {string} */
            category: "RealTime" | "PlannedWork" | "Information" | "Incident" | "Undefined";
            category_description: string;
            description: string;
            summary: string;
            affected_routes: string[];
            affected_stops: components["schemas"]["AffectedStop"][];
            closure_text: string;
            severity: number;
            /** Format: date-time */
            created: string;
            /** Format: date-time */
            last_update: string;
        };
        /**
         * @description NaPTAN code resolved to a human-readable station name when
         *     possible. ``name`` is ``null`` when neither the static
         *     dim_stations seed nor the TfL /StopPoint fallback could match
         *     the code (e.g. deprecated NaPTANs); the frontend renders the
         *     raw ``naptan_id`` in that case.
         */
        AffectedStop: {
            naptan_id: string;
            name?: string | null;
        };
        ChatRequest: {
            thread_id: string;
            message: string;
        };
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant" | "system";
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description One leg of a planned journey. */
        JourneyLeg: {
            mode: string;
            summary: string;
            minutes: number;
        };
        /**
         * @description Structured payload of a `journey` SSE frame (the `content` field is
         *     this object JSON-encoded). Built from `plan_journey_tool`.
         */
        JourneyView: {
            total_minutes: number;
            start: string;
            arrival: string;
            legs: components["schemas"]["JourneyLeg"][];
        };
        /** @description One predicted arrival at a platform. */
        ArrivalPrediction: {
            line: string;
            destination?: string | null;
            seconds: number;
        };
        /** @description Upcoming arrivals grouped under a single platform. */
        ArrivalsPlatform: {
            platform: string;
            arrivals: components["schemas"]["ArrivalPrediction"][];
        };
        /**
         * @description Structured payload of an `arrivals` SSE frame (the `content` field
         *     is this object JSON-encoded). Built from `get_arrivals_tool`.
         */
        ArrivalsView: {
            station: string;
            platforms: components["schemas"]["ArrivalsPlatform"][];
        };
        /** @description RFC 7807 problem details. */
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
        };
    };
    responses: {
        /** @description Error response following RFC 7807. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "dependencies": {}
                     *     }
                     */
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    get_status_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live line statuses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "line_id": "victoria",
                     *         "line_name": "Victoria",
                     *         "mode": "tube",
                     *         "status_severity": 10,
                     *         "status_severity_description": "Good Service",
                     *         "reason": null,
                     *         "valid_from": "2026-04-22T07:00:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       },
                     *       {
                     *         "line_id": "piccadilly",
                     *         "line_name": "Piccadilly",
                     *         "mode": "tube",
                     *         "status_severity": 6,
                     *         "status_severity_description": "Severe Delays",
                     *         "reason": "Signal failure at Acton Town",
                     *         "valid_from": "2026-04-22T06:15:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       },
                     *       {
                     *         "line_id": "elizabeth",
                     *         "line_name": "Elizabeth line",
                     *         "mode": "elizabeth-line",
                     *         "status_severity": 9,
                     *         "status_severity_description": "Minor Delays",
                     *         "reason": "Earlier incident at Paddington",
                     *         "valid_from": "2026-04-22T05:30:00Z",
                     *         "valid_to": "2026-04-22T23:59:59Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["LineStatus"][];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    get_recent_disruptions: {
        parameters: {
            query?: {
                limit?: number;
                mode?: "tube" | "elizabeth-line" | "overground" | "dlr" | "bus" | "national-rail" | "river-bus" | "cable-car" | "tram";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent disruptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "disruption_id": "2026-04-22-PIC-001",
                     *         "category": "RealTime",
                     *         "category_description": "Real Time",
                     *         "description": "Signal failure at Acton Town, reduced service on Piccadilly.",
                     *         "summary": "Severe delays on Piccadilly line",
                     *         "affected_routes": [
                     *           "piccadilly"
                     *         ],
                     *         "affected_stops": [
                     *           {
                     *             "naptan_id": "940GZZLUACT",
                     *             "name": "Acton Town"
                     *           },
                     *           {
                     *             "naptan_id": "940GZZLUBSC",
                     *             "name": "Barons Court"
                     *           }
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 6,
                     *         "created": "2026-04-22T06:15:00Z",
                     *         "last_update": "2026-04-22T08:05:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-ELI-001",
                     *         "category": "RealTime",
                     *         "category_description": "Real Time",
                     *         "description": "Earlier incident at Paddington affecting Elizabeth line.",
                     *         "summary": "Minor delays on Elizabeth line",
                     *         "affected_routes": [
                     *           "elizabeth"
                     *         ],
                     *         "affected_stops": [
                     *           {
                     *             "naptan_id": "910GPADTON",
                     *             "name": "Paddington"
                     *           }
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 6,
                     *         "created": "2026-04-22T05:40:00Z",
                     *         "last_update": "2026-04-22T07:20:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-21-VIC-001",
                     *         "category": "PlannedWork",
                     *         "category_description": "Planned Work",
                     *         "description": "Engineering works affecting Victoria line weekend service.",
                     *         "summary": "Minor delays this weekend",
                     *         "affected_routes": [
                     *           "victoria"
                     *         ],
                     *         "affected_stops": [],
                     *         "closure_text": "No service between Seven Sisters and Walthamstow Central on Sunday.",
                     *         "severity": 9,
                     *         "created": "2026-04-18T12:00:00Z",
                     *         "last_update": "2026-04-21T09:00:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-PIC-002",
                     *         "category": "Information",
                     *         "category_description": "Information",
                     *         "description": "Lifts out of service at Holborn.",
                     *         "summary": "Step-free access affected",
                     *         "affected_routes": [
                     *           "piccadilly"
                     *         ],
                     *         "affected_stops": [
                     *           {
                     *             "naptan_id": "940GZZLUHBN",
                     *             "name": "Holborn"
                     *           }
                     *         ],
                     *         "closure_text": "",
                     *         "severity": 9,
                     *         "created": "2026-04-22T04:00:00Z",
                     *         "last_update": "2026-04-22T04:00:00Z"
                     *       },
                     *       {
                     *         "disruption_id": "2026-04-22-VIC-002",
                     *         "category": "Information",
                     *         "category_description": "Information",
                     *         "description": "Reduced frequency during morning peak due to staff shortage.",
                     *         "summary": "Change of frequency on Victoria line",
                     *         "affected_routes": [
                     *           "victoria"
                     *         ],
                     *         "affected_stops": [],
                     *         "closure_text": "",
                     *         "severity": 9,
                     *         "created": "2026-04-22T06:30:00Z",
                     *         "last_update": "2026-04-22T07:45:00Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Disruption"][];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    post_chat_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    get_chat_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chat history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "role": "user",
                     *         "content": "Is the Piccadilly line running normally right now?",
                     *         "created_at": "2026-04-20T14:12:00Z"
                     *       },
                     *       {
                     *         "role": "assistant",
                     *         "content": "Yes — the Piccadilly line is reporting Good Service at the moment.",
                     *         "created_at": "2026-04-20T14:12:04Z"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["ChatMessage"][];
                };
            };
            404: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
}
